### ISSUE TITLE
fb-client hang a little when use pipe.

### ISSUE THREAD

**Issue by Catofes** [Bluewind/filebin#10]
When I use fb-client in terminal, the script will hang if I pipe the fb's output to other programs until use mouse to drag the terminal.  While everything is fine if I do not pipe.  
The Picture show blow:

![image](https://cloud.githubusercontent.com/assets/3324513/18807156/d05c815a-8205-11e6-93a8-d2a360f70ef1.png)

Everything works fine if I do not pipe the fb out.

![image](https://cloud.githubusercontent.com/assets/3324513/18807163/e1815bae-8205-11e6-8767-2f297726f89c.png)

The script hang. Until I select some character in the terminal. 

![image](https://cloud.githubusercontent.com/assets/3324513/18807182/44e8c2f4-8206-11e6-86ec-255297ca6628.png)

My fb-client version is 2.0.2 and my Desktop Environment is Gnome3.

**Comment by Bluewind** [comment]
Thanks for the report. I've fixed the bug in 2.0.3. Please test it and confirm that it works for you too.
