### ISSUE TITLE
[Database] Change database's default port.

### ISSUE THREAD

**Issue by Catofes** [Bluewind/filebin#12]
I found that after I set 
```
$db['default']['hostname'] = "127.0.0.1:5433";
```
in `database.php`, the web get database error. Is there anyway that can change database's default port?

**Comment by Bluewind** [comment]
You can change the port by adding a line like this

```php
$db['default']['port'] = 5433;
```

Does that work for you? If so I'll add it to the example.

**Comment by Catofes** [comment]
Yep, It works. Thank you very much.
