### ISSUE TITLE
backtrace trying to pastebin a public key

### ISSUE THREAD

**Issue by gregf** [Bluewind/filebin#19]
I'm on the latest git stable release (just pulled now). I am unable as of recently to pastebin my public key. Every time I try I get the following error in my log files.

```
2017/09/27 14:32:29 [error] 1320#1320: *23830 FastCGI sent in stderr: "PHP message: Exception 1/1 'ErrorException' with message 'filesize(): stat failed for /home/filebin/www/filebin/public_html//../data/uploads/08c/08cc4214fa8d5a97bf06f729f608e90b-456' in /home/filebin/www/filebin/application/helpers/filebin_helper.php:348
Backtrace:
#0 /home/filebin/www/filebin/public_html/index.php(207): libraries\ExceptionHandler::error_handler(2, 'filesize(): stat failed for /home/filebin/www/filebin/public_html//../data/uploads/08c/08cc4214fa8d5a97bf06f729f608e90b-456', '/home/filebin/www/filebin/application/helpers/filebin_helper.php', 348)
#1 unknown file(unknown line): _exception_handler(2, 'filesize(): stat failed for /home/filebin/www/filebin/public_html//../data/uploads/08c/08cc4214fa8d5a97bf06f729f608e90b-456', '/home/filebin/www/filebin/application/helpers/filebin_helper.php', 348, Array)
#2 /home/filebin/www/filebin/application/helpers/filebin_helper.php(348): filesize('/home/filebin/www/filebin/public_html//../data/uploads/08c/08cc4214fa8d5a97bf06f729f608e90b-456')
```

I'm able to upload other files just fine. I gave the file to my friend he was able to upload it to his pastebin that he runs without issues. So I have a feeling it's specific to mine, just don't know what is wrong.

**Comment by gregf** [comment]
Oh PHP 7.0.22 on Ubuntu 16.04

**Comment by Bluewind** [comment]
The code tries to check if the newly uploaded file is the same as an already existing one with the same md5 hash, but it looks like the code is unable to properly check that.

Does the file `/home/filebin/www/filebin/public_html//../data/uploads/08c/08cc4214fa8d5a97bf06f729f608e90b-456` exist and if so can the user that php is running under access that path? A good way to check is `namei -l /home/filebin/www/filebin/public_html//../data/uploads/08c/08cc4214fa8d5a97bf06f729f608e90b-456`.

If the permissions are wrong, please fix them.

If the file does not exist, you'll have to manually remove it from the database:
```mysql
delete from `file_storage` where id=456;
```

Whatever solution works, please tell me.

**Comment by gregf** [comment]
Permissions are fine. I don't see a file_storage table in the ttrss database. I'm getting 

```
ERROR 1146 (42S02): Table 'ttrss.ttrss_file_storage' doesn't exist
```

**Comment by Bluewind** [comment]
Why are you looking in the ttrss database instead of the one for filebin?

**Comment by gregf** [comment]
Because I just woke up at 3am and I'm a moron :) Sorry!

**Comment by gregf** [comment]
OK Deleting it from the database seemed to have worked, thank you!
