### ISSUE TITLE
Database Error: Dupblicate Entry

### ISSUE THREAD

**Issue by gregf** [Bluewind/filebin#22]
```
 A Database Error Occurred
Error Number: 1062
Duplicate entry 'r90h36ti4r89p1saajblosps8cvkmbot' for key 'PRIMARY'
INSERT INTO `ci_sessions` (`id`, `ip_address`, `timestamp`, `data`) VALUES
('r90h36ti4r89p1saajblosps8cvkmbot', 'xxx.xxx.xxx.xxx.', 1514132898, '__ci_last_regenerate|i:1
14132897;logged_in|b:1;username|s:13:\"Dave\";userid|s:1:\"2\";access_level|s:4:\"
full\";')
```

**Comment by Bluewind** [comment]
What did you do to provoke this and does the problem persist or does it work if you try again?

**Comment by gregf** [comment]
I have a small server with 4 or 5 users. One of the users told me he was getting this error a day or two ago, I hadn't even done a git pull since the last release let alone touch the server.

The problem persists.

**Comment by Bluewind** [comment]
I'm afraid I can't reproduce this, but I might see a possibility in the code that could cause it. Can you try if it still happens with this patch applied? https://paste.xinu.at/Yx8/
You can use curl https://paste.xinu.at/Yx8 | git apply; to apply it

**Comment by gregf** [comment]
Merry Late Christmas Blue. I asked him to login again after applying the patch and he says he gets the same error as before.

**Comment by Bluewind** [comment]
Do you have the ``$config['sess_match_ip']`` setting enabled in config-local.php? In that case you'd have to adjust the primary key of the ci_sessions table to also include the ip_address column, but changing the databse layout may cause issues with automatic database migrations in the future.

**Comment by gregf** [comment]
Yep, I had that enabled. Disabled it and he was able to login. Thanks for the fix.
