### ISSUE TITLE
qr code library missing from php composer?

### ISSUE THREAD

**Issue by gregf** [Bluewind/filebin#32]
I'm seeing the following error after trying to do some debugging. When I try to visit any `<id>/qr` url I get a empty box.

```
An unhandled error occured.

Exception 1 of 1
Fatal error: Uncaught exception Error
Message: Class 'Endroid\QrCode\QrCode' not found
Backtrace:
#0 /var/www/application/controllers/Main.php(32): Main->_download()
#1 /var/www/system/core/CodeIgniter.php(532): Main->index()
#2 /var/www/public_html/index.php(372): require_once('/var/www/system/core/CodeIgniter.php')
#3 /var/www/index.php(10): include('/var/www/public_html/index.php')
thrown in /var/www/application/controllers/Main.php on line 149
```

**Comment by Bluewind** [comment]
That code is included in `application/third_party/QrCode` via a git submodule. You may need to run `git submodule update --init --recursive`, which is also part of the installation instructions. It is run by the `./git-hooks/post-merge` script at the end of the installation.
